### PR TITLE
Add intellisense instructions to readme

### PR DESCRIPTION
**Pull request by jxxe**
I added a brief note about VS Code intellisense (see #124)

### CODE REVIEW

**Comment by jxxe** [comment]
Here's a preview:
image

**Comment by jaredh159** [comment]
hey, appreciate the PR, i think documenting intellisense in the readme is a good idea.

question though -- seems like most of the examples over in #124 reference the `tw` identifier somehow, but your recommended simplest way only references `style`.  will this work for most use cases?  i'm a bit out of my depth here, because i don't use vscode, and i'm actually not currently actively working on any project that uses `twrnc`.

**Comment by jxxe** [comment]
I modified the instructions to include both. Using the style attribute is more complete but also less precise. The regex solution is more precise but less complete, if that makes any sense. Using both provides a pretty good balance.

**Comment by jaredh159** [comment]
excellent, thanks so much, merging. appreciate it. 👍

**Pull request merged**
