### PR TITLE
chore: add React to peer dependencies

### PR DESCRIPTION
**Pull request by nbennink**
Adding this project to my react-native-web project keeps resulting in the error: `React is not defined`. React is currently only added to the dev dependencies, I believe it should also be added to the peerDependencies to indicate that it's required for this package to run in production.

### CODE REVIEW

**Comment by jaredh159** [comment]
@nbennink thanks for the PR.

I'm a bit confused though why you'd be getting an error `React is not defined` if you have react installed (even as a dev dependency). 

I'm not a huge fan of peer dependencies, I feel like they just create warnings that people ignore, or cause other confusion, and you're the first person I've ever heard say they got this error.  I guess I'd like to make sure there wasn't something else going on in your case before adding this.  Is your project open source? Or could you provide an open source repro of the issue?

**Comment by jaredh159** [comment]
Or maybe a better question is why do you have react installed as a _dev_ dependency?

**Comment by nbennink** [comment]
My bad, React is currently only added to the dev dependencies of `twrnc`.

The problem is probably that this is not a normal React Native project. I have a mono repo with a React app. Within that monorepo is another package written with React Native and `twrnc`. The React Native imports are resolved to react-native-web which is why I can use React Native components within a normal React web. But this project is therefore not using Metro but our own Webpack configuration.

I can check if I can setup a simple repository with reproduce steps.

**Comment by jaredh159** [comment]
I'm gonna close this for now, but I'm happy to reopen if you have a simple repro or more details. Seems like you're setup is pretty unique.

**Pull request closed without merging**
