### PR TITLE
support tw vertical align utilities

### PR DESCRIPTION
**Pull request by menghany**

### CODE REVIEW

**Comment by jaredh159** [comment]
hi there! thanks for the PR!

i think CI will fail because of formatting things, a quick way to fix it is just run `npm run lint:fix` and `npm run format`.

question, is this PR essentially implementing the android-only `verticalAlign` text style prop from here? https://reactnative.dev/docs/text-style-props#verticalalign-android

(i'm fine adding an android-only utility, just want to be clear what these map to)

**Comment by menghany** [comment]
> hi there! thanks for the PR!
> 
> i think CI will fail because of formatting things, a quick way to fix it is just run `npm run lint:fix` and `npm run format`.
> 
> question, is this PR essentially implementing the android-only `verticalAlign` text style prop from here? https://reactnative.dev/docs/text-style-props#verticalalign-android
> 
> (i'm fine adding an android-only utility, just want to be clear what these map to)

 Yes, as you said. This is a text style prop that only exists on android.

**Comment by jaredh159** [comment]
ok, thanks. i'm good with this addition. but, before i merge, can you remove the new test file you created, and add the test cases to `src/__tests__/simple-mappings.spec.ts` instead? i think they fit in neatly there and don't warrant their own test file.

**Comment by menghany** [comment]
Sure, I have moved over.

**Comment by jaredh159** [comment]
released in `v4.1.0`. thanks for the contribution!

**Pull request merged**
