### PR TITLE
changed map+filter to filterMap

### PR DESCRIPTION
**Pull request by ibnlanre**
- Used a filterMap instead of a combined map and filter.
- Removed the comment as there is nothing wrong with mutating an object when it's not the one being traversed.

### CODE REVIEW

**Comment by jaredh159** [comment]
i'm a bit mystified here... `.filterMap` is not a javascript function, as far as I'm aware.

**Comment by ibnlanre** [comment]
I'm so sorry. I meant to use .flatMap

**Comment by jaredh159** [comment]
no problem. :)  however, i don't think we want to flatMap here, flatMap flattens nested arrays while mapping, and we don't have nested arrays being produced, i'm just executing a little side-effect while mapping (which is why i put in the comment, because theoretically functions passed to .map should be perfectly pure, and free from side-effects)

**Comment by jaredh159** [comment]
i appreciate the PR, but I don't think I'm going to merge this.  I don't see any real win here... the assignment within the use of the comma operator is a bit hard to understand and first glance, and doesn't buy us any speed, so I don't think it's worth the cost of the less straightforward code. 

but i appreciate your time, and thanks for being willing to contribute!

**Comment by ibnlanre** [comment]
it's a pleasure.

**Pull request closed without merging**
